apiVersion: v1
kind: Pod
metadata:
  name: postgres-client-pod
spec:
  containers:
  - name: postgres-client-container
    image: postgres
    command: ["/bin/sleep", "infinity"]
    stdin: true
    tty: true
